PracticaSimetrica/Models/ErrorViewModel.cs
using System;

namespace PracticaSimetrica.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticaSimetrica/Controllers/BaseController.cs
using IBusinessLogic.IBaseService;
using Microsoft.AspNetCore.Mvc;

namespace PracticaSimetrica.Controllers
{
    public class BaseController<T> : Controller where T: class
    {
        private readonly IBaseService<T> _bs;
        public BaseController(IBaseService<T> bs)
        {
            _bs = bs;
        }

        [HttpPost]
        public virtual IActionResult Agregar(T entity)
        {
            if (ModelState.IsValid)
            {
                    _bs.Agregar(entity);
            }

            return View(entity);
        }

        [HttpGet]
        public IActionResult Obtener()
        {
            return View(_bs.Obtener().result);
        }

        [HttpGet]
        public IActionResult ObtenerPorId(int id)
        {
            return View(_bs.ObtenerPorId(id).result);
        }

        [HttpPost]
        public IActionResult Editar(T entity)
        {
            if (ModelState.IsValid)
            {
                _bs.Editar(entity);
            }

            return View();
        }

        [HttpGet]
        public virtual IActionResult Eliminar(int id)
        {
            _bs.Eliminar(id);
            return View();
        }
    }
}

PracticaSimetrica/Controllers/CandidatoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IBusinessLogic.Candidatos;
using IBusinessLogic.Evaluaciones;
using Database.OperationResult;
using Database.Models;

namespace PracticaSimetrica.Controllers
{
    public class CandidatoController : BaseController<Candidato>
    {
        private readonly ICandidatosService _serviceCandidatos;
        private readonly IEvaluacionesService _serviceEvaluaciones;
        public CandidatoController(ICandidatosService serviceC, IEvaluacionesService serviceE)
            : base(serviceC)
        {
            _serviceCandidatos = serviceC;
            _serviceEvaluaciones = serviceE;
        }

        [HttpGet]
        public IActionResult RegistroCandidatos()
        {
            return View();
        }

        [HttpPost]
        public override IActionResult Agregar(Candidato candidato)
        {
            base.Agregar(candidato);
            return RedirectToAction("Obtener");
        }

        [HttpGet]
        public IActionResult ModificacionCandidato(int id)
        {
            var model = _serviceCandidatos.obtenerCandidatoPorId(id);

            return View(model.result);
        }

        [HttpPost]
        public IActionResult ModificacionCandidato(Candidato candidato)
        {
            if (ModelState.IsValid)
            {
                _serviceCandidatos.modificarCandidato(candidato);
                return RedirectToAction("Obtener");
            }
            return View(candidato);
        }

        [HttpGet]
        public override IActionResult Eliminar(int id)
        {
            _serviceEvaluaciones.eliminarEvaluaciones(id);
            base.Eliminar(id);
            return RedirectToAction("Obtener");
        }
    }
}

PracticaSimetrica/Controllers/EvaluacionesController.cs
using Microsoft.AspNetCore.Mvc;
using IBusinessLogic.Evaluaciones;
using Database.Models;

namespace PracticaSimetrica.Controllers
{
    public class EvaluacionesController : Controller
    {
        private readonly IEvaluacionesService _serviceEvaluaciones;


        public EvaluacionesController(IEvaluacionesService Eservice)
        {
            _serviceEvaluaciones = Eservice;
        }

        [HttpGet]
        public IActionResult RegistroEvaluaciones(int id_candidato)
        {
            var model = _serviceEvaluaciones.obtenerEvaluacion(id_candidato).result;

            return View(model);
        }

        [HttpPost]
        public IActionResult RegistroEvaluaciones(CandidatoEvaluacion ev)
        {
            if (ModelState.IsValid)
            {
                _serviceEvaluaciones.evaluarCandidato(ev.evaluacion);
                return RedirectToAction("Obtener", "Candidato");
            }

            return View(ev);
        }

        [HttpGet]
        public IActionResult ObtenerEvaluacion(int id)
        {
            var resultado = _serviceEvaluaciones.obtenerEvaluacion(id).result;

            return View(resultado);
        }
    }
}

PracticaSimetrica/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PracticaSimetrica.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PracticaSimetrica.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Candidato()
        {
            return RedirectToAction("ObtenerCandidatosRegistrados", "Candidato");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticaSimetrica/Views/Candidato/ModificacionCandidato.cshtml
@model Database.Models.Candidato

@{
    ViewData["Title"] = "ModificacionCandidato";
}

<h4>Modificar datos de @Model.nombre @Model.apellido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ModificacionCandidato">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="id" name="id" class="form-control" hidden value="@Model.id"/>
            </div>
            <div class="form-group">
                <label class="control-label">Nombre</label>
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Apellido</label>
                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Edad</label>
                @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Fecha de nacimiento</label>
                @Html.EditorFor(model => model.fecha_nacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_nacimiento, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Cédula</label>
                @Html.EditorFor(model => model.cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cedula, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Modificar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Candidato" asp-action="Obtener">Regresar a la lista de candidatos</a>
</div>

PracticaSimetrica/Views/Candidato/Obtener.cshtml
@model IEnumerable<Database.Models.Candidato>

@{
    ViewData["Title"] = "Candidatos";
}

<h1>Candidatos registrados</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Apellido
            </th>
            <th>
                Edad
            </th>
            <th>
                Fecha de nacimiento
            </th>
            <th>
                Cedula
            </th>
            <th>
                Accion
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.edad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha_nacimiento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cedula)
                </td>
                <td>
                    @Html.ActionLink("Evaluar", "RegistroEvaluaciones", "Evaluaciones", new { id_candidato = item.id }) |
                    @Html.ActionLink("Ver evaluaciones", "ObtenerEvaluacion", "Evaluaciones", new { id = item.id }) |
                    @Html.ActionLink("Modificar", "ModificacionCandidato", new { id = item.id }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.id } )
                    
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<input type="button" class="btn btn-primary" value="Registrar un candidato" onclick="location.href='@Url.Action("RegistroCandidatos")'" />

PracticaSimetrica/Views/Candidato/RegistroCandidatos.cshtml
@model Database.Models.Candidato

@{
    ViewData["Title"] = "RegistrarCandidato";
}

<h1>Registrar un candidato</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Agregar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Nombre</label>
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Apellido</label>
                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellido,"", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Edad</label>
                @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Fecha de Nacimiento</label>
                @Html.EditorFor(model => model.fecha_nacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_nacimiento, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Cedula</label>
                @Html.EditorFor(model => model.cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cedula, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Obtener">Regresar a la lista de candidatos</a>
</div>

PracticaSimetrica/Views/Evaluaciones/ObtenerEvaluacion.cshtml
@model Database.Models.CandidatoEvaluacion

@{
    ViewData["Title"] = "ObtenerEvaluacion";
}

<div>
    <h3>Evaluaciones de @Model.candidato.nombre @Model.candidato.apellido</h3>
    <hr />
    @if (Model.listaEvaluaciones.Count > 0)
    {
        @foreach (var item in Model.listaEvaluaciones)
        {
            <dl class="row">
                <dt class="col-sm-10">
                    ID de la evaluacion
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => item.id)
                </dd>
                <dt class="col-sm-10">
                    Fecha de la evaluación
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => item.fecha_evaluacion)
                </dd>
                <dt class="col-sm-10">
                    Resultado del examen psicológico
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => item.resultado_examen_psicologico)
                </dd>
                <dt class="col-sm-10">
                    Resultado del examen de algoritmos
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => item.resultado_examen_algoritmos)
                </dd>
                <dt class="col-sm-10">
                    Resultado del examen de SQL
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => item.resultado_examen_sql)
                </dd>
                <dt class="col-sm-10">
                    Total
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => item.resultado_final)
                </dd>
                <dt class="col-sm-10">
                    Condición
                </dt>
                @if (item.resultado_final > 6)
                {
                    <dd class="col-sm-10">
                        Aprobado
                    </dd>
                }
                else
                {
                    <dd class="col-sm-10">
                        Reprobado
                    </dd>
                }

            </dl>
            <hr />
        }
    }
    else
            {
                <h5>Este candidato aún no ha sido evaluado</h5>
                <br/>
                <br/>
            }

</div>
<div>
    @Html.ActionLink("Regresar a la lista de candidatos", "Obtener", "Candidato")
</div>

PracticaSimetrica/Views/Evaluaciones/RegistroEvaluaciones.cshtml
@model Database.Models.CandidatoEvaluacion

@{
    ViewData["Title"] = "Evaluar";
}
<h4>Evaluar a @Model.candidato.nombre @Model.candidato.apellido</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="RegistroEvaluaciones">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="evaluacion.id_candidato" value="@Model.evaluacion.id_candidato" class="form-control" hidden />
            </div>
            <div class="form-group">
                <label class="control-label">Fecha de la evaluación</label>
                @*<input asp-for="evaluacion.fecha_evaluacion" asp-format="{0:dd/MM/yyyy}" class="form-control" />*@
                @Html.EditorFor(model => model.evaluacion.fecha_evaluacion, new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.evaluacion.fecha_evaluacion, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Resultado del examen psicológico</label>
                @Html.EditorFor(model => model.evaluacion.resultado_examen_psicologico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluacion.resultado_examen_psicologico, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Resultado del examen de algoritmos</label>
                @Html.EditorFor(model => model.evaluacion.resultado_examen_algoritmos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluacion.resultado_examen_algoritmos, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Resultado del examen de SQL</label>
                @Html.EditorFor(model => model.evaluacion.resultado_examen_sql, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluacion.resultado_examen_sql, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Resultado total</label>
                @Html.EditorFor(model => model.evaluacion.resultado_final, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evaluacion.resultado_final, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Registrar evaluación" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Regresar a la lista de candidatos", "Obtener", "Candidato")
</div>

PracticaSimetrica/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3>Bienvenido al sistema de evaluación de candidatos</h3>
</div>

PracticaSimetrica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Evaluación de candidatos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidato" asp-action="Obtener">Candidatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>